---
baseURL: "https://fpvhub.ch"
title: "fpvhub.ch"
theme: "hugo-theme-monochrome"
defaultContentLanguage: de
languages:
  de:
    disabled: false
    languageCode: "de"
    languageName: "Deutsch"
    contentDir: "content"
    weight: 1

params:
  footer: "Copyright © 2023 by oxivanisher" 
  author: "oxivanisher" 

menu:
  navbar:
  - identifier: news
    name: News
    url: /news/
    weight: 10
  - identifier: discord
    name: Discord
    url: /discord
    weight: 20
  - identifier: infos
    name: Infos
    url: /infos
    weight: 30
  - identifier: kleine-helfer
    name: "Kleine Helfer"
    url: /kleine-helfer
    weight: 40
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 100


