baseURL = 'https://fpvhub.ch/'
title = 'fpvhub.ch'
author = 'the-techna'
paginate = 3
theme = 'arabica'

[params]
    description = "Swiss FPV Hub"
    dateFormatToUse = "02.01.2006"
    replaceGoogleFonts = "fonts.loli.net"